language: python
python:
  - "2.7"
# command to install dependencies

sudo: required

services:
  - docker

before_install:
- docker pull library/redis
- docker run -d redis
install:
  - pip install -r requirements.txt
# command to run tests
script:
  -  pytest


